codecov:
    token: 40f53a18-2bdf-4652-9ba6-3efdc50e47b7  # Token is only necessary for as long as this repo is private
    notify:
        require_ci_to_pass: yes

coverage:
    range: 70..100
    round: nearest
    precision: 2
    status:
        project:
            default: True
        patch:
            default: True
        changes: yes

comment:
    require_changes: yes
