codecov:
    notify:
        require_ci_to_pass: yes

coverage:
    range: 70..100
    round: nearest
    precision: 2
    status:
        project:
            default: True
        patch:
            default: True
        changes: yes

comment:
    require_changes: yes
