codecov:
    token: 3dce9231-5b59-428c-b708-0b5ec1be2f30  # Token is only necessary for as long as this repo is private
    notify:
        require_ci_to_pass: yes

coverage:
    range: 70..100
    round: nearest
    precision: 2
    status:
        project:
            default: True
        patch:
            default: True
        changes: yes

comment:
    require_changes: yes
