sudo: required
dist: xenial
language: python 

notifications:
  email:
    recipients:
      - jseiler@swin.edu.au 
    on_success: change
    on_failure: always

matrix:

  include:
    - os: linux
      python: "3.7"

    - os: osx 
      python: "3.7"

before_install:
  - sudo apt-get update -q
  - pip install -r requirements.txt

script:
  - pytest
