sudo: required
dist: xenial
language: python 

notifications:
  email:
    recipients:
      - jseiler@swin.edu.au 
    on_success: change
    on_failure: always

matrix:

  include:
    - os: linux
      python: "3.7"

    - os: osx 
      python: "3.7"
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS

before_install:
	- |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          sudo apt-get update -q
      else
          brew update
          brew upgrade python
			fi
  - pip install -r requirements.txt

script:
  - pytest
